services:
  app:
    build: ./Backend
    container_name: absence_backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb+srv://aassaf4516_db_user:sKcrByxKghJG3uOM@cluster0.hfy5fyw.mongodb.net/
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:latest
    container_name: absence_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - C:/Users/hp/Desktop/DB:/data/db
    environment:
      MONGO_INITDB_DATABASE: absence_management

volumes:
  mongo_data:
